# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d95a3619287eb86fca3f1cc962d2180889b4c29907e60aa70cd80f0845ed6161122ccc9b0fbc871c71bc03669aee3d6b71b2ec84dc845f09530cfda4b9eb228e

test:
  secret_key_base: 14e1dcd1cfc99852f319652e3a3ec620527a5ecb252c0c2d784c050703bfe02f48f10e5d216d301e77ee83bf26a9b318701776d259ef1cd955ea9d56b0f9503d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
